### ISSUE TITLE
Update for wp-cli 2.5.0 compatibility, rework tests to use testing framework

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pb-cli#58]
See:

- https://make.wordpress.org/cli/2021/05/19/wp-cli-v2-5-0-release-notes/
- https://github.com/wp-cli/wp-cli-tests

**Comment by greatislander** [comment]
@SteelWagstaff Can you assign this to me?

**Comment by SteelWagstaff** [comment]
Done. Thanks! FYI, we're going to be pulling Sentry out of core Pressbooks ASAP, hopefully in time for next planned release (5.21.0) next week.
